### ISSUE TITLE
点击 "." 怎么替换为"0." 呢,例如 输入的金额是 0.1 ,不是 .1

### ISSUE THREAD

**Issue by kolvs** [zuiwuyuan/WeChatPswKeyboard#1]
点击 "." 怎么替换为"0." 呢,例如 输入的金额是 0.1 ,不是 .1

**Comment by zuiwuyuan** [comment]
@assess15 ，自己监听Edittext的TextWatcher内容变化，如果第一个字符是"."然后动态修改显示内容为“0.”
